### PR TITLE
added console.log to www to display the port in the terminal

### PR DESCRIPTION
**Pull request by mjhea0**

### CODE REVIEW

**Comment by dougwilson** [comment]
What's wrong with using the DEBUG environment? Also tests are failing.

**Comment by mjhea0** [comment]
I teach using the express generator and DEBUG confuses people. Just tired of telling people to log it to the console.

**Comment by dougwilson** [comment]
Gotcha. So if we make this change, we don't want to have two things logging to the console. I would say replace the existing one and the new one needs to have a way to turn it off (say, off if in production).

**Comment by dougwilson** [comment]
Closing due to lack of action on the last comment. If you can address it, let me know and I can always open the PR again or you can always make a new PR :)

**Pull request closed without merging**
