### PR TITLE
4.14

### PR DESCRIPTION
**Pull request by williammincy**
+ Created command line option that consolidates all template engines under one --view option
+ Updated README.md with instructions on usage
+ Created tests and ensured they passed

### CODE REVIEW

**Comment by williammincy** [comment]
Hoping this helps push the next release out since the last item for the branch was just getting all the template options under one parameter. Let me know if any changes or additions are needed.

**Comment by dougwilson** [comment]
Awesome! Can you make it such that `--view foo` throws an error for unknown view instead of defaulting to jade? Otherwise, it will be really hard to add new views.

**Comment by williammincy** [comment]
Done. I've made it so that passing no argument to --view returns an error and usage instructions. Also please note that I didn't remove any of the other arguments for specifying templates as I didn't know if you wanted that done or not. The task was just adding the consolidated --view option.

**Comment by williammincy** [comment]
it looks like the AppVeyor build failed due to a timeout but I installed the version of node it was testing against and seems to pass in my VM. Not sure if you need me to refactor the tests to get them to pass or if you can assign more time to allow them to pass, but let me know if I need to do anything else for the pull request to be accepted.

**Comment by dougwilson** [comment]
I started a new run of the AppVeyor tests. The one that failed took 60 minutes, so it must have gotten flat stuck somewhere, so seems fine.

**Comment by kushvarma** [comment]
When we can have 4.14 ready? Travis seams fine. It can be merged right?

**Comment by williammincy** [comment]
Great! Please let me know if there is anything else I can do to help get the next official release ready.

**Comment by dougwilson** [comment]
This has _finally_ made it into the pending 4.14 changes. Thanks again for all your hard work!

**Pull request closed without merging**
