### PR TITLE
Simplified default error handler

### PR DESCRIPTION
**Pull request by miletbaker**
In an attempt to apply DRY principles and make app.js more
readable. I have merged the development and production error handlers
together. Also as express is often used for JSON APIs, I suggest we
use res.format to cover several use cases. Tests have been updated and all are
passing.

I'm also wondering if we should extract this along with the 404 handler into a separate middleware. In my own project I've moved these into a middleware/errorHandlers.js file. This makes app.js clearer and also acts as an example to new users on how to structure and include middleware. I accept this would be starting to introduce opinion and convention but experienced developers would know how to restructure to their liking. The additional benefit is that app.js is then more focussed on setup and configuration and leaves implementation to other modules.

In any case, feel free to merge or if you would like me to separate this out as suggested then let me know and I'll get onto it.

### CODE REVIEW

**Comment by miletbaker** [comment]
Not sure why AppVeyor is failing, seems to be missing a dependance: acorn/util/walk 

see https://ci.appveyor.com/project/dougwilson/generator/build/41/job/wyxhhq2xs5xip0hd#L53

I don't think I've changed anything to break this but let me know.

**Comment by dougwilson** [comment]
I like how this shows how to use the content negotiation as well.

**Comment by dougwilson** [comment]
Sorry this got closed from some GitHub voodoo. It doesn't have the option for me to re-open it form some reason! :( Please re-create your pull request.

**Comment by miletbaker** [comment]
@dougwilson sorry for being out of the conversation. GitHub had not sent me any of the above notification but got the last one above. I still have my fork but I had not pulled sown the newer commits. Do you want me to reopen from that?

**Pull request closed without merging**
