### PR TITLE
Updates the Express version to ~4.14.0

### PR DESCRIPTION
**Pull request by mAiNiNfEcTiOn**
# What does this PR do:
Updates the `express` dependency to version `4.14.0`, to tackle this issue:

screen shot 2016-10-06 at 20 41 23

### CODE REVIEW

**Comment by dougwilson** [comment]
Can you make the PR against the 4.14.0 branch, which is the branch we are using to track the next release?

**Comment by dougwilson** [comment]
Sorry "4.14" branch.

**Comment by mAiNiNfEcTiOn** [comment]
HI @dougwilson, sure I can! Doing now.

**Comment by dougwilson** [comment]
Thank you! I just tried to merge but it failed saying "empty commit". Apparently the 4.14 branch already has this changed :) !

**Pull request closed without merging**
