### PR TITLE
deps: replace jade with pug

### PR DESCRIPTION
**Pull request by hacksparrow**
Replace jade with pug, because of https://github.com/pugjs/pug/issues/2184.

### CODE REVIEW

**Comment by lordKnighton** [comment]
In general LGTM

**Comment by crandmck** [comment]
Can this be merged?  
We've updated docs to refer to `pug` instead of `jade` everywhere (https://github.com/expressjs/expressjs.com/issues/609), but of course, we won't update docs for the generator until this is merged and the repo is republished to npm.

**Comment by dougwilson** [comment]
I was waiting for pug to at least not be an alpha? Do we know if it is actually released yet? Though jade is deprecated, it's just that: deprecated, not gone. It's still just as usable while deprecated.

**Comment by crandmck** [comment]
I see @dougwilson thx for the update.

> waiting for pug to at least not be an alpha? Do we know if it is actually released yet?

From what I can see on npm, looks like it's still 2.0.0-alpha6
The repo has lots of recent commits, so yeah, I guess we'll just keep waiting for it to come out of alpha.

**Comment by ayesham** [comment]
pug is now 2.0.0-beta3 in npm. Can this be merged please?

**Comment by dougwilson** [comment]
No. Either this PR needs to add pug as a new, separate option from jade or we need to wait for an actual stable version of pug.

**Comment by dougwilson** [comment]
I suggest updating the PR to make pug a new option, keeping jade as the default. Then we can release with pug and when pug is eventually stable, we can consider swapping the default. It sucks that the project owners of jade decided to deprecate all version of jade with no real path forward, but there isn't much we can do about their decisions :(

**Comment by dougwilson** [comment]
For those those who want to follow up with the pug team, https://github.com/pugjs/pug/issues/2405 may be the most relevant issue to follow up on.

**Comment by hacksparrow** [comment]
@dougwilson https://github.com/expressjs/generator/pull/115 is a PR for adding Pug template support.

**Comment by dougwilson** [comment]
Sorry this got closed from some GitHub voodoo. It doesn't have the option for me to re-open it form some reason! :( Please re-create your pull request.

**Comment by dougwilson** [comment]
No need to re-open; this is being handled by PR #118

**Pull request closed without merging**
