### PR TITLE
Express 4.16.2 with built-in body parser

### PR DESCRIPTION
**Pull request by gonenduk**
Express 4.16.2 includes a security fix and body-parser built-in. No need to require it anymore.
Makes the code smaller and more simple.

### CODE REVIEW

**Comment by dougwilson** [comment]
Thanks! Looks like a duplicate of #173

**Comment by gonenduk** [comment]
When will PR #173 be merged into master and published in npm?

**Comment by dougwilson** [comment]
Just need to get the PR listed in thr checkbox at the top working and merged. Anyone is welcome to help out! I don't get paid so don't reallt have a time commit myself, but others may :) !

**Comment by dougwilson** [comment]
I'll try to work on it today but depending on what is going on at work may or may not have time.

**Comment by gonenduk** [comment]
That could be great. Thanks!
Let me know if you guys need any help...

**Pull request closed without merging**
