### PR TITLE
Resolved issue #109

### PR DESCRIPTION
**Pull request by dmsakamoto**
Changed all `jade` references to `pug`. `jade` is deprecated and was renamed `pug`.

- Updated generator to load `pug` instead of `jade`
- Updated `jade` templates to `pug` templates
- Updated tests to look for `pug` instead of `jade`

All tests pass
screen shot 2016-04-13 at 7 26 51 pm
screen shot 2016-04-13 at 7 26 39 pm

### CODE REVIEW

**Comment by dougwilson** [comment]
What is the difference between this pull request and the existing one #107?

**Comment by dmsakamoto** [comment]
I think one test failed on the last pull request. It was looking for `npm` dependencies in a different order when `jade` changed to `pug`. We will be sure when the CI finishes

**Comment by dougwilson** [comment]
All tests are passing in #107.

**Comment by dmsakamoto** [comment]
Then my bad

**Comment by dmsakamoto** [comment]
Though, this is the latest version of `pug@2.0.0-alpha3`. #107 is version `pug@2.0.0-alpha1`

**Comment by dougwilson** [comment]
Sorry this got closed from some GitHub voodoo. It doesn't have the option for me to re-open it form some reason! :( Please re-create your pull request.

**Comment by dougwilson** [comment]
No need to re-open; this is being handled by PR #118

**Pull request closed without merging**
