### PR TITLE
replace individual template options with a single one (--view <engine>) ...

### LINKED ISSUE #41: The -h option to express is listed twice
The -h option was previously used for help.  Now it is used for handlebars.  I noticed this when doing express -h in a non-empty directory and getting prompted as follows:

```
destination is not empty, continue?
```

$ ./bin/express --help

  Usage: express [options] [dir]

  Options:

```
-h, --help          output usage information
-V, --version       output the version number
-e, --ejs           add ejs engine support (defaults to jade)
-h, --hbs           add handlebars engine support
-H, --hogan         add hogan.js engine support
-c, --css <engine>  add stylesheet <engine> support (less|stylus|compass) (defaults to plain css)
-f, --force         force on non-empty directory
```

### PR DESCRIPTION
**Pull request by azat-co**
...fix #41 :circus_tent: :cow:

### CODE REVIEW

**Comment by nicolasmccurdy** [comment]
:+1:

**Comment by dougwilson** [comment]
Sorry this got closed from some GitHub voodoo. It doesn't have the option for me to re-open it form some reason! :( Please re-create your pull request.

**Comment by azat-co** [comment]
@dougwilson wow, this is super old... let me take a look :)

**Comment by azat-co** [comment]
@dougwilson here you go #120

**Comment by dougwilson** [comment]
Thank you, @azat-co!

**Comment by azat-co** [comment]
@dougwilson cool to see it finally merged!

**Pull request closed without merging**
