### PR TITLE
When forced, check if there's an existing package.json and clone dependencies

### PR DESCRIPTION
**Pull request by codinger41**
When the command is forced on a directory that isn't empty, my changes will check if the user has an existing package.json file and clone it's dependencies instead of overwriting it.

### CODE REVIEW

**Comment by leksyib** [comment]
@dougwilson hey man, do you have any idea why the tests aren't passing on on travis? it passes on appveyor and locally.

**Comment by leksyib** [comment]
@rwky

**Comment by rwky** [comment]
Probably a good idea if it merges here too https://github.com/expressjs/generator/blob/master/bin/express-cli.js#L477

Tests need adding and README needs updating.

**Comment by dougwilson** [comment]
I'm going to close this for now and the requested changed have not been made after a year. If you are still interested in making them, feel free to open a new pull request with the requested changes made.

**Pull request closed without merging**
