### PR TITLE
Adds the ability to generate a project using ES2015 template

### PR DESCRIPTION
**Pull request by bluzi**
Hi guys, 

I added ES2015 support to the generator exactly as discussed in [this issue](https://github.com/expressjs/generator/issues/167)
The generator detects whether it is running on a Node version that supports ES2015, and if it does, it will generate a project using the ES2015 templates. Otherwise, it will generate a project using the good old ES5 templates.

I also added two additional flags: `--es5` and `--es2015` - using one of them will force the generator to use one of these templates, regardless of the Node version.

The ES2015 support detection is provided using [feature-detect-es6](https://www.npmjs.com/package/feature-detect-es6). I tested it a lot and it works flawlessly. 

I tested it using the following Node versions, and it works as expected: 
- v0.10.48
- v4.8.4
- v6.11.4
- v8.6.0  

Please let me know if you want any changes, or if you have any feature suggestions or anything like that.

### CODE REVIEW

**Comment by bluzi** [comment]
Looks like AppVeyor fails because of the changes I've made in README.md. That's weird. :/

**Comment by dougwilson** [comment]
This is awesome, thank you! I would really love to get it included in the 4.16 release I was working on before you made your PR, but I haven't released yet. I changed the PR to base on the 4.16 branch, but it looks like there are conflicts it would be great if you could help resolve.

Also, can you add tests for the new command line switches?

**Comment by bluzi** [comment]
Sure

**Comment by bluzi** [comment]
I'm closing this PR, since I created new one with the changes you requested.
Please refer to [the new PR](https://github.com/expressjs/generator/pull/176)

**Pull request closed without merging**
