### PR TITLE
Bumped EJS dependency to ~2.0.0

### PR DESCRIPTION
**Pull request by mde**
Work on v2 is happening here: https://github.com/mde/ejs I'm the new package maintainer.

### CODE REVIEW

**Comment by dougwilson** [comment]
Thanks, @mde :) This would have actually happened earlier, but when I tried, my tests failed, which is why I ended up filing those two bug reports to you :)!

**Comment by mde** [comment]
Thank you so much for those fixes! I was in such a hurry to reimplement the few missing features and land v2, that I hadn't linted the code. You may notice there's now a .jshintrc file, so there shouldn't be any regressions of that type. I'll be excited to see more people moving up to v2!

**Comment by dougwilson** [comment]
Yea, me too. A few months ago I was considering volunteering to take over ejs, but never did because I don't have the time to take that on :) Glad to see it with an owner once again.

**Comment by mde** [comment]
:+1:

**Comment by dougwilson** [comment]
I altered you PR to `~2.1.4`

**Comment by mde** [comment]
Sounds great. They'll both pick up minor version updates. Thanks for merging this so swiftly.

**Comment by dougwilson** [comment]
No problem :) Feel free to send over a PR if there is some time you really want the version here bumped and I haven't already done so !

**Pull request closed without merging**
